services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/data.sqlite
    volumes:
      - dbdata:/app/data
    restart: unless-stopped

volumes:
  dbdata:
