services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/data.sqlite
      - CLIENT_ORIGIN=http://localhost:8080
    volumes:
      - dbdata:/app/data
    restart: unless-stopped

  web:
    build:
      context: ./client
      args:
        # What the built UI will call at runtime (browser hits your host)
        VITE_API_URL: http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

  jmeter:
    image: justb4/jmeter:latest
    depends_on:
      - api
    volumes:
      - ./perf/jmeter:/test
      - ./perf/results:/results
    command: >
      -n -t /test/issue-api.jmx
      -Jserver=api
      -Jport=3000
      -l /results/result.jtl
      -e -o /results/report

volumes:
  dbdata:
