name: Build & Push Docker images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-images
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  OWNER_LC: ${{ toLower(github.repository_owner) }}
  IMAGE_API: ghcr.io/${{ toLower(github.repository_owner) }}/issue-tracker-api
  IMAGE_WEB: ghcr.io/${{ toLower(github.repository_owner) }}/issue-tracker-web
  # Change this if your hosted UI should talk to a different API URL:
  VITE_API_URL: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ===== API image =====
      - name: Meta (API)
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_API }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Build & Push (API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      # ===== Web image =====
      - name: Meta (Web)
        id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_WEB }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha

      - name: Build & Push (Web)
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
          build-args: |
            VITE_API_URL=${{ env.VITE_API_URL }}
